## Aula 03
Introdução a aula 03

- Biblioteca Pandas
- Biblioteca Numpy
 
 ```python
 print("Olá mundo")
 ```
 1. Conhecendo a biblioteca
 2. Executando Comandos

In [1]:
import pandas as pd 
import numpy as np

In [3]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos = ["Pastel","Caçulinha","Refrigerante","Combos"]

array_produtos = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_produtos * array_precos
for nome,preco in zip(nomes_produtos,faturamento):
    print(f"{nome} : {preco}")

Pastel : 30
Caçulinha : 25
Refrigerante : 42
Combos : 1000

### Exercício de fixação 
- Criar uma lista que ira possuir 10 nomes de produtos.
- Criar uma lista que ira possuir o preço de custo (Atacado).
- Criar uma lista que irá possuir o preço de venda (Varejo).
- Ao final, exibir o lucro obtido em cada produto.

In [4]:
quantidade_produtos = [10,6,10,30,12,6,24,12,24,12]
precos_produtos_atacado = [20,14,55,4,5,30,18,30,20,40]
precos_produtos_varejo = [5,35,10,8,10,7,4,7,4,10]
nomes_produtos = ["Kit de Meias","Pulverizador Manual 2L","Toalha Umedecida","Esmaltes Variados","Porta Comprimidos Semanal","Bebidas Fardo Refri 2L","Detergente Líquido 500ml","Creme Dental","Sabonete em Barra","Desodorante Spray/Roll-on"]

array_precos01 = np.array(precos_produtos_atacado)
array_precos02 = np.array(precos_produtos_varejo)

lucro = array_precos01 - array_precos02
lucro_obtido = np.sum(lucro)
print(f"O lucro obtido foi R${lucro_obtido}")

for nome,preco in zip(nomes_produtos,lucro):
    print(f"{nome} : {preco}")

O lucro obtido foi R$136
Kit de Meias : 15
Pulverizador Manual 2L : -21
Toalha Umedecida : 45
Esmaltes Variados : -4
Porta Comprimidos Semanal : -5
Bebidas Fardo Refri 2L : 23
Detergente Líquido 500ml : 14
Creme Dental : 23
Sabonete em Barra : 16
Desodorante Spray/Roll-on : 30

# Pandas

In [ ]:
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head() #Por padrão, ele exibe as 5 primeiras informações

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [30]:
df.tail() #Exibe as 5 ultimas

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [31]:
#Dimensões da tabela
df.shape

(40, 6)

In [32]:
df.columns

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     object
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), object(1)
memory usage: 2.0+ KB

In [34]:
#Contar valores duplicados
df.drop_duplicates().sum()

id_registro                                                    820
setor            MontagemUsinagemUsinagemUsinagemUsinagemUsinag...
temperatura_c                                              2901.03
tempo_ciclo_s                                              1404.13
producao_dia                                                  4656
falha                                                           12
dtype: object

In [35]:
# Contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [36]:
# Proura por valores não nulos
df.notnull().sum()

id_registro      40
setor            40
temperatura_c    40
tempo_ciclo_s    40
producao_dia     40
falha            40
dtype: int64

In [37]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [38]:
#Registro de temperatura
df["temperatura_c"]

0     72.62
1     81.65
2     68.87
3     66.84
4     66.23
5     64.79
6     85.02
7     60.31
8     75.84
9     68.38
10    76.31
11    74.79
12    76.31
13    63.28
14    64.98
15    81.48
16    79.62
17    69.80
18    77.16
19    73.30
20    79.77
21    71.76
22    74.16
23    74.69
24    74.03
25    75.96
26    60.80
27    69.37
28    70.28
29    73.53
30    63.59
31    68.91
32    77.62
33    73.32
34    78.24
35    68.47
36    75.62
37    78.50
38    76.19
39    68.64
Name: temperatura_c, dtype: float64

In [44]:
import pandas as pd
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head()

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [47]:
#
df[["temperatura_c","falha"]]

    temperatura_c  falha
0           72.62      0
1           81.65      0
2           68.87      0
3           66.84      0
4           66.23      0
5           64.79      0
6           85.02      1
7           60.31      0
8           75.84      0
9           68.38      1
10          76.31      0
11          74.79      0
12          76.31      0
13          63.28      0
14          64.98      0
15          81.48      0
16          79.62      1
17          69.80      0
18          77.16      0
19          73.30      1
20          79.77      0
21          71.76      0
22          74.16      0
23          74.69      1
24          74.03      1
25          75.96      0
26          60.80      0
27          69.37      1
28          70.28      0
29          73.53      0
30          63.59      1
31          68.91      0
32          77.62      1
33          73.32      1
34          78.24      0
35          68.47      0
36          75.62      1
37          78.50      0
38          76.19      1
39          68.64      0

In [49]:
#Criar uma nova coluna relacionando dados 
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"Temperatura Alta", "Temperatura_baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,Temperatura_baixa
1,2,Usinagem,81.65,34.08,128,0,Temperatura Alta
2,3,Usinagem,68.87,39.44,159,0,Temperatura_baixa
3,4,Usinagem,66.84,34.52,98,0,Temperatura_baixa
4,5,Usinagem,66.23,31.57,94,0,Temperatura_baixa

Subir a base de dados
- Mostrar os 5 primeiros registros
- Mostrar os 5 ultimos 
- Mostrar o tamanho
- Mostrar a descrição

In [23]:
df = pd.read_csv(r".\data\dataset_techshop_vendas.csv")
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [24]:
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [25]:
df.shape

(800, 7)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    object
 1   categoria        800 non-null    object
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    object
 5   canal_marketing  800 non-null    object
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 43.9+ KB